
INSERT INTO catprodutos (cat_id, cat_descr) VALUES (1, 'XIS');
INSERT INTO catprodutos (cat_id, cat_descr) VALUES (2, 'REFRIS');
INSERT INTO catprodutos (cat_id, cat_descr) VALUES (3, 'PIZZAS');
INSERT INTO catprodutos (cat_id, cat_descr) VALUES (4, 'CALZONES');
--

INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (1, 'Cebola', 'Cebola Frita', 1, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (2, 'Batata Frita', 'Batata Frita', 1, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (101, 'ALLA BARRIGA', 'mussarela, tomate, calabresa picada, champignon, azeitona picante, pimentão, manjericão e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (102, 'ALLA BLUM', 'mussarela, calabresa, alho picado, ovo, pimentão, tomate e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (103, 'ALLA DOUTORAS', 'mussarela, abacaxi, bacon e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (104, 'ALLA FELTES', 'mussarela, bacon, ovo, azeitona, provolone e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (105, 'ALLA FUORTE', 'mussarela, alho e óleo e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (106, 'ALLA NANDO', 'mussarela, frango, tomate seco, provolone, óleo de oliva e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (107, 'ALLA ORKUT', 'mussarela, strogonoff, champignon e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (108, 'ALLA PORCHER (Sérgio Porcher)', 'mussarela, palmito, salsinha, atum, parmesão e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (109, 'ALLA TIÇÃO (Moda da Casa)', 'mussarela, frango, bacon frito, parmesão, requeijão e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (110, 'ALLA TININHA', 'mussarela, presunto, cebola, pimentão, ovos, azeitona, milho, calabresa picada, alho e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (111, 'ALLA WIRTH', 'mussarela, tomate, tomate seco, gorgonzola, champignon, manjericão, óleo de oliva, copa, ervilha e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (112, 'ALLA WEB (Webplash)', 'mussarela, filé, alho, provolone, catupiry e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (113, 'DIOGUITO', 'mussarela, filé ao molho branco c/ alho, pomodoro, champignon e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (114, 'DON ALEX', 'mussarela, milho e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (115, 'DON LUCCA (Lucas Dietrich)', 'mussarela, copa, requeijão, ovo e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (116, 'DON OLIVIO', 'mussarela, copa, tomate seco, gorgonzola, azeite de oliva e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (117, 'DON PEDROT', 'mussarela, palmito, brócolis, champignon, pimentão e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (118, 'DON RIGGO', 'mussarela, pimentão, brócolis, tomate, ovo, requeijão e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (119, 'FUNDO DEL MAR', 'mussarela, camarão a molho especial e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (120, 'ITALIANÍSSIMA', 'mussarela, calabresa, alho e óleo, parmesão e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (121, 'MANNÜ', 'mussarela, berinjela temperada, tomate seco, azeitona picante, champignon e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (122, 'SIRACUZZA', 'mussarela, brócolis, catupiry, provolone e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (201, '5 QUEIJOS', 'mussarela, parmesão, provolone, gorgonzola, requeijão e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (202, 'ATUM', 'mussarela, atum e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (203, 'CALABRESA', 'mussarela, calabresa e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (204, 'CHAMPIGNON', 'mussarela e champignon', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (205, 'CORAÇÃO', 'mussarela, coração e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (206, 'CORLLEONE', 'mussarela, azeitona temperada, cebola e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (207, 'FILÉ', 'mussarela, filé, batata palha e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (208, 'MARGHERITA à moda Italiana', 'mussarela, rodelas de tomate, parmesão, manjericão, óleo de oliva e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (209, 'NAPOLITANA', 'mussarela, salame italiano, requeijão e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (210, 'PALMITO', 'mussarela, palmito e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (211, 'PIEMONTE', 'mussarela, atum, ovos, gorgonzola e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (212, 'PORTUGUESA', 'mussarela, presunto, cebola, pimentão, ovos, azeitona e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (213, 'ROMANA', 'mussarela, calabresa, tomate, cebola, catupiry e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (214, 'SIRACUZZA', 'mussarela, brócolis, catupiry, provolone e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (215, 'STROGONOFF', 'mussarela, strogonoff, champignon e molho de tomate', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (301, 'BRIGADEIRO', 'brigadeiro', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (302, 'CALIFÓRNIA', 'pêssego, figo e abacaxi', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (303, 'CHOCOLATE BRANCO', 'chocolate branco e leite condensado', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (304, 'CHOCOLATE PRETO', 'chocolate preto e leite condensado', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (305, 'CÔCO', 'côco ralado e leite condensado', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (306, 'DIÉRICK (Diego e Érick)', 'brigadeiro, morango, pêssego e leite condensado', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (307, 'DON RODRIGUES', 'mussarela, chocolate branco, chocolate preto, côco, banana, pêssego e leite condensado', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (308, 'MESCLADO', 'chocolate branco, chocolate preto e leite condensado', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (309, 'PRESTÍGIO', 'côco ralado, chocolate preto e leite condensad', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (310, 'SAN DANIELO D''FRAGOLI', 'chocolate preto, chocolate branco, uva e morango', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (311, 'SANDI', 'chocolate preto e morango', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (312, 'SUSPIRATTO (Pizza do Brasileiro)', 'banana c/ canela, açucar ou gemada', 3, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (401, 'ALLA NAPOLITANA', 'mussarela, salame italiano e ovo', 4, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (402, 'ALL''EMILIANA', 'mussarela, presunto, parmesão e salsa', 4, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (403, '5 FORMAGGI', 'mussarela, parmesão, provolone, gorgonzola e catupiry', 4, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (404, 'VIAREGGIO', 'mussarela, calabresa, tomate seco e provolone', 4, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (405, 'ALLA MONDRAGONE', 'mussarela, palmito, aspargos, ervilha e ovo', 4, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (406, 'PIEMONTE', 'mussarela, frango, ervilha e ovo', 4, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (407, 'PINEROLO', 'mussarela e coração de galinha', 4, NULL);
INSERT INTO catprodutos_itens (cpi_id, cpi_item, cpi_descr, cpi_catid, cpi_valor) VALUES (408, 'ALLA PORTO FINO', 'mussarela, atum, ervilha, ovo e azeitona temperada', 4, NULL);

SET client_encoding = 'LATIN1';
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;


INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (1, 'PIZZA FAMILIA', 29.00, NULL, NULL, '0', 3);
INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (2, 'PIZZA BROTO', 14.00, NULL, NULL, '0', 3);
INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (3, 'PIZZA MEDIA', 16.00, NULL, NULL, '0', 3);
INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (4, 'PIZZA GRANDE', 19.00, NULL, NULL, '0', 3);
INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (5, 'CAlZONES', 16.00, NULL, NULL, '0', 4);
INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (50, 'AGUA TONICA LATA', 1.50, NULL, NULL, '1', 2);
INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (51, 'COCA COLA LATA', 1.50, NULL, NULL, '1', 2);
INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (52, 'COCA-COLA LITRO', 2.75, NULL, NULL, '1', 2);
INSERT INTO produtos (pro_id, pro_nome, pro_preco, pro_descr, pro_foto, pro_estoque, pro_catid) VALUES (53, 'COCA-COLA 2 LITROS', 3.75, NULL, NULL, '1', 2);
